import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { Redirect, useRouter } from "expo-router";
import { api } from "../src/api";
import { authToken } from "../src/session";

export default function MapView() {
  const router = useRouter(); const [trips, setTrips] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [busy, setBusy] = useState(true);
  const token = authToken;
  const load = useCallback(async () => { if (!token) return; try { const result = await api.listTrips(token); setTrips(result.trips); setSelected(result.trips[0] || null); } finally { setBusy(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  if (!token) return <Redirect href="/login" />;
  const stops = selected ? (selected.itinerary.days || []).flatMap((day: any) => (day.activities || []).map((activity: any) => ({ ...activity, day: day.day_number }))).filter((activity: any) => activity.lat != null && activity.lng != null) : [];
  return <SafeAreaView style={styles.safe}><View style={styles.page}><View style={styles.nav}><Pressable onPress={() => router.push("/planner")}><Text style={styles.back}>Plan</Text></Pressable><Text style={styles.title}>Trip map</Text><Pressable onPress={() => router.push("/trips")}><Text style={styles.back}>Trips</Text></Pressable></View>{busy ? <View style={styles.center}><ActivityIndicator color="#d95a41" /></View> : !selected ? <View style={styles.center}><Text style={styles.empty}>Save a trip to see its stops.</Text></View> : <ScrollView contentContainerStyle={styles.content}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{trips.map((trip) => <Pressable key={trip.id} onPress={() => setSelected(trip)} style={[styles.chip, selected.id === trip.id && styles.chipActive]}><Text style={selected.id === trip.id ? styles.chipTextActive : styles.chipText}>{trip.itinerary.destination}</Text></Pressable>)}</ScrollView><View style={styles.map}><Text style={styles.mapTitle}>{selected.itinerary.destination}</Text><Text style={styles.mapSub}>Activity coordinates</Text>{stops.map((stop: any) => <View key={`${stop.day}-${stop.title}`} style={styles.stop}><View style={styles.pin}><Text style={styles.pinText}>{stop.day}</Text></View><View><Text style={styles.stopTitle}>{stop.title}</Text><Text style={styles.stopMeta}>Day {stop.day} · {stop.lat.toFixed(3)}, {stop.lng.toFixed(3)}</Text></View></View>)}</View></ScrollView>}</View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f9f6f0" }, page: { flex: 1, maxWidth: 760, width: "100%", alignSelf: "center" }, nav: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 24, borderBottomWidth: 1, borderBottomColor: "#e5e0d8" }, title: { color: "#1a1a1a", fontSize: 22, fontWeight: "700" }, back: { color: "#b5412a", fontWeight: "600" }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 }, empty: { color: "#555", fontSize: 18 }, content: { padding: 24 }, chips: { gap: 8, paddingBottom: 18 }, chip: { borderWidth: 1, borderColor: "#d7d0c5", borderRadius: 20, paddingHorizontal: 14, paddingVertical: 9 }, chipActive: { backgroundColor: "#d95a41", borderColor: "#d95a41" }, chipText: { color: "#333" }, chipTextActive: { color: "#fff", fontWeight: "600" }, map: { minHeight: 420, backgroundColor: "#e7eee6", borderRadius: 16, padding: 20, borderWidth: 1, borderColor: "#cad8c9" }, mapTitle: { color: "#1a1a1a", fontSize: 26, fontWeight: "700" }, mapSub: { color: "#4f7054", marginTop: 4, marginBottom: 24 }, stop: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "rgba(255,255,255,0.82)", padding: 12, borderRadius: 10, marginBottom: 10 }, pin: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#d95a41", alignItems: "center", justifyContent: "center" }, pinText: { color: "#fff", fontWeight: "700" }, stopTitle: { color: "#1a1a1a", fontWeight: "600" }, stopMeta: { color: "#6b6b6b", marginTop: 3 } });
