import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Animated, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { Redirect, useRouter } from "expo-router";
import { api } from "../src/api";
import { authToken } from "../src/session";

function TripCard({ trip, index, onPress }: { trip: any; index: number; onPress: () => void }) {
  const progress = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    const animation = Animated.timing(progress, { toValue: 1, duration: 600, delay: index * 110, useNativeDriver: false });
    animation.start();
    return () => animation.stop();
  }, [index, progress]);
  const translateY = progress.interpolate({ inputRange: [0, 1], outputRange: [22, 0] });
  const opacity = progress.interpolate({ inputRange: [0, 1], outputRange: [0, 1] });
  const palette = index % 3 === 0 ? styles.sageCard : index % 3 === 1 ? styles.ochreCard : styles.terracottaCard;
  const plan = trip.itinerary;
  return <Animated.View style={{ opacity, transform: [{ translateY }] }}><Pressable style={[styles.card, palette]} onPress={onPress}><View style={styles.cardTop}><Text style={styles.cardKicker}>ESCAPE 0{index + 1}</Text><Text style={styles.leaf}>✦</Text></View><View><Text style={styles.cardTitle}>{plan.trip_title}</Text><Text style={styles.destination}>{plan.destination}</Text><Text style={styles.cardSummary} numberOfLines={2}>{plan.summary}</Text></View><View style={styles.cardBottom}><View><Text style={styles.metaLabel}>DURATION</Text><Text style={styles.metaValue}>{plan.duration_days} days</Text></View><View><Text style={styles.metaLabel}>BUDGET</Text><Text style={styles.metaValue}>{plan.currency} {plan.total_budget}</Text></View><Text style={styles.openArrow}>↗</Text></View></Pressable></Animated.View>;
}

export default function Trips() {
  const router = useRouter(); const [trips, setTrips] = useState<any[]>([]); const [busy, setBusy] = useState(true); const token = authToken;
  const load = useCallback(async () => { if (!token) return; setBusy(true); try { setTrips((await api.listTrips(token)).trips); } finally { setBusy(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  if (!token) return <Redirect href="/login" />;
  return <SafeAreaView style={styles.safe}><View style={styles.page}><View style={styles.nav}><Pressable onPress={() => router.push("/planner")}><Text style={styles.back}>← Plan</Text></Pressable><Text style={styles.logo}>YOUR ESCAPES</Text><Pressable onPress={() => router.push("/profile")}><Text style={styles.back}>Profile</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>THE COLLECTION</Text><Text style={styles.heading}>Places worth leaving for.</Text><Text style={styles.intro}>{trips.length ? `${trips.length} little adventure${trips.length === 1 ? "" : "s"} waiting in your pocket.` : "Your next story starts with a blank page."}</Text>{busy ? <View style={styles.loading}><ActivityIndicator color="#55735b" /><Text style={styles.muted}>Gathering your escapes...</Text></View> : trips.length === 0 ? <View style={styles.emptyCard}><Text style={styles.emptyLeaf}>⌁</Text><Text style={styles.empty}>Nothing saved yet.</Text><Text style={styles.muted}>Ask the planner for somewhere with a little more sky.</Text><Pressable style={styles.button} onPress={() => router.push("/planner")}><Text style={styles.buttonText}>Start planning</Text><Text style={styles.buttonArrow}>↗</Text></Pressable></View> : trips.map((trip, index) => <TripCard key={trip.id} trip={trip} index={index} onPress={() => router.push({ pathname: "/trip/[id]", params: { id: trip.id } })} />)}</ScrollView></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f1eee5" }, page: { flex: 1, maxWidth: 820, width: "100%", alignSelf: "center" }, nav: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 26, paddingVertical: 20, borderBottomWidth: 1, borderBottomColor: "#dcd7cb" }, logo: { color: "#344c39", fontSize: 13, fontWeight: "800", letterSpacing: 2 }, back: { color: "#55735b", fontSize: 13, fontWeight: "700" }, content: { padding: 24, paddingBottom: 60 }, kicker: { color: "#c45a3f", fontSize: 11, fontWeight: "800", letterSpacing: 1.6 }, heading: { color: "#293c2e", fontSize: 38, lineHeight: 43, fontWeight: "800", marginTop: 9 }, intro: { color: "#6b7167", fontSize: 16, lineHeight: 23, marginTop: 10, marginBottom: 25 }, card: { borderRadius: 20, padding: 22, minHeight: 226, marginBottom: 15, justifyContent: "space-between", overflow: "hidden" }, sageCard: { backgroundColor: "#d5dfcf" }, ochreCard: { backgroundColor: "#e5c478" }, terracottaCard: { backgroundColor: "#dfaa95" }, cardTop: { flexDirection: "row", justifyContent: "space-between" }, cardKicker: { color: "rgba(41,60,46,0.65)", fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, leaf: { color: "rgba(41,60,46,0.7)", fontSize: 23 }, cardTitle: { color: "#293c2e", fontSize: 25, lineHeight: 30, fontWeight: "800", maxWidth: 570 }, destination: { color: "#55735b", fontSize: 15, fontWeight: "800", marginTop: 4 }, cardSummary: { color: "#566256", fontSize: 14, lineHeight: 20, marginTop: 10, maxWidth: 570 }, cardBottom: { flexDirection: "row", alignItems: "flex-end", gap: 28, marginTop: 20 }, metaLabel: { color: "rgba(41,60,46,0.6)", fontSize: 9, fontWeight: "800", letterSpacing: 1 }, metaValue: { color: "#293c2e", fontSize: 13, fontWeight: "800", marginTop: 3 }, openArrow: { color: "#293c2e", fontSize: 28, marginLeft: "auto" }, loading: { minHeight: 180, justifyContent: "center", alignItems: "center", gap: 12 }, muted: { color: "#6b7167", lineHeight: 22 }, emptyCard: { backgroundColor: "#fffaf1", borderWidth: 1, borderColor: "#dfd6c7", borderRadius: 20, padding: 24, alignItems: "center", marginTop: 8 }, emptyLeaf: { color: "#c45a3f", fontSize: 34, marginBottom: 10 }, empty: { color: "#293c2e", fontSize: 23, fontWeight: "800", marginBottom: 7 }, button: { backgroundColor: "#55735b", minHeight: 48, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 11, paddingHorizontal: 18, marginTop: 24, width: "100%" }, buttonText: { color: "#fff", fontWeight: "800", fontSize: 15 }, buttonArrow: { color: "#fff", fontSize: 19 } });
