import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { api } from "../../src/api";
import { authToken } from "../../src/session";

export default function TripDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter();
  const [trip, setTrip] = useState<any>(null); const [expenses, setExpenses] = useState<any[]>([]); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [busy, setBusy] = useState(true);
  const load = useCallback(async () => { if (!authToken || !id) return; setBusy(true); try { const [tripResult, expenseResult] = await Promise.all([api.getTrip(authToken, id), api.listExpenses(authToken, id)]); setTrip(tripResult); setExpenses(expenseResult.expenses); } finally { setBusy(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  async function addExpense() { const value = Number(amount); if (!authToken || !id || !value || value <= 0) return; await api.addExpense(authToken, id, { category: "other", amount: value, note }); setAmount(""); setNote(""); load(); }
  async function remove() { if (authToken && id) { await api.deleteTrip(authToken, id); router.replace("/trips"); } }
  if (busy) return <View style={styles.center}><ActivityIndicator color="#d95a41" /></View>;
  if (!trip) return <View style={styles.center}><Text>Trip not found.</Text></View>;
  const plan = trip.itinerary; const spent = expenses.reduce((total, item) => total + Number(item.amount), 0);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>Back to trips</Text></Pressable><Text style={styles.title}>{plan.trip_title}</Text><Text style={styles.destination}>{plan.destination} · {plan.duration_days} days · {plan.currency} {plan.total_budget}</Text><Text style={styles.summary}>{plan.summary}</Text>{(plan.days || []).map((day: any) => <View key={day.day_number} style={styles.day}><Text style={styles.dayTitle}>Day {day.day_number} · {day.title}</Text>{(day.activities || []).map((activity: any) => <Text key={activity.title} style={styles.activity}>{activity.time}  {activity.title} · {plan.currency} {activity.cost}</Text>)}</View>)}<View style={styles.budget}><Text style={styles.section}>Budget</Text><Text style={styles.total}>{plan.currency} {spent.toFixed(2)} spent of {plan.total_budget}</Text><TextInput placeholder="Expense amount" keyboardType="decimal-pad" value={amount} onChangeText={setAmount} style={styles.input} /><TextInput placeholder="What was it?" value={note} onChangeText={setNote} style={styles.input} /><Pressable style={styles.button} onPress={addExpense}><Text style={styles.buttonText}>Add expense</Text></Pressable>{expenses.map((expense) => <Text key={expense.id} style={styles.expense}>{expense.note || expense.category} · {plan.currency} {expense.amount}</Text>)}</View><Pressable onPress={remove}><Text style={styles.delete}>Delete this trip</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f9f6f0" }, center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#f9f6f0" }, content: { padding: 24, maxWidth: 760, width: "100%", alignSelf: "center" }, back: { color: "#b5412a", fontWeight: "600", marginBottom: 28 }, title: { color: "#1a1a1a", fontSize: 34, fontWeight: "700" }, destination: { color: "#b5412a", fontWeight: "600", marginTop: 8 }, summary: { color: "#555", lineHeight: 23, marginTop: 16 }, day: { borderTopWidth: 1, borderTopColor: "#e5e0d8", marginTop: 22, paddingTop: 16 }, dayTitle: { color: "#1a1a1a", fontWeight: "700", marginBottom: 8 }, activity: { color: "#555", lineHeight: 26 }, budget: { backgroundColor: "#fff", borderColor: "#e5e0d8", borderWidth: 1, borderRadius: 16, padding: 18, marginTop: 28 }, section: { color: "#1a1a1a", fontSize: 20, fontWeight: "700" }, total: { color: "#4f7054", marginTop: 6, marginBottom: 14 }, input: { borderColor: "#d7d0c5", borderWidth: 1, borderRadius: 10, padding: 12, marginTop: 8 }, button: { backgroundColor: "#d95a41", borderRadius: 10, minHeight: 44, alignItems: "center", justifyContent: "center", marginTop: 10 }, buttonText: { color: "#fff", fontWeight: "600" }, expense: { color: "#555", marginTop: 12 }, delete: { color: "#b23a3a", textAlign: "center", marginTop: 28, paddingBottom: 30 } });
